import Head from "next/head";
import { useForm } from "react-hook-form";
import axios from "axios";

export default function Home() {
  const url = "http://localhost:3000";
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm();

  const onSubmit = (data) => {
    axios
      .post(url + "/api/signup", data)
      .then((res) => {
        console.log("back", res);
      })
      .catch((err) => {
        console.log("err", err);
      });
  };

  return (
    <div className="container">
      <Head>
        <title>Twitch Tools</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="mainTitle">
          Welcome to <span> Twitch Tools</span> !
        </h1>
        <section className="mainContainer">
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Porro
            magni quod, aut aliquam expedita fugiat quidem eligendi quibusdam ab
            perspiciatis ad, dolor necessitatibus quae repellendus nostrum nemo
            molestias? Blanditiis, minus.
          </p>
          <form onSubmit={handleSubmit(onSubmit)}>
            <input {...register("name")} />
            <input {...register("email")} />
            <input {...register("password")} />
            <input type="submit" />
          </form>
        </section>
      </main>
    </div>
  );
}
