import Head from "next/head";


export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Twitch Tools</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="mainTitle">Welcome to <span> Twitch Tools</span> !</h1>
        <section className="mainContainer">
        
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Porro
            magni quod, aut aliquam expedita fugiat quidem eligendi quibusdam ab
            perspiciatis ad, dolor necessitatibus quae repellendus nostrum nemo
            molestias? Blanditiis, minus.
          </p>
          <form action="">
            <input type="text" />
            <input type="text" />
          </form>
        </section>
      
      </main>

      <footer className="footer">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
     
        </a>
      </footer>
    </div>
  );
}
